name = "TensorNetworkQuantumSimulator"
uuid = "4de3b72a-362e-43dd-83ff-3f381eda9f9c"
license = "MIT"
version = "0.2.2"
authors = ["JoeyT1994 <jtindall@flatironinstitute.org>", "MSRudolph <manuel.rudolph@web.de>", "and contributors"]
description = "A Julia package for quantum simulation with tensor networks of near-arbritrary topology."

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
EinExprs = "b1794770-133b-4de1-afb4-526377e9f4c5"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
PauliPropagation = "293282d5-3c99-4fb6-92d0-fd3280a19750"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimpleGraphAlgorithms = "41400c72-0c58-5c16-8579-4ecbce768449"
SimpleGraphConverter = "205b04f2-f585-4877-a239-566270b3f673"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[compat]
Adapt = "4.3.0"
Combinatorics = "1.0.3"
Dictionaries = "0.4"
EinExprs = "0.6.4"
Format = "1.3.7"
GraphRecipes = "0.5.13"
Graphs = "1.8.0"
HyperDualNumbers = "4.0.10"
IJulia = "1.32.1"
ITensorMPS = "0.3.17"
ITensors = "0.9"
JLD2 = "0.6.2"
KrylovKit = "0.10.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
NamedGraphs = "0.7"
PauliPropagation = "0.3.0"
Plots = "1.41.1"
PythonPlot = "1.0.6"
Revise = "3.8.0"
SimpleGraphAlgorithms = "0.6.0"
SimpleGraphConverter = "0.1.0"
SplitApplyCombine = "1.2.3"
Statistics = "1.11.1"
StatsBase = "0.34.4"
TensorOperations = "5.2"
TypeParameterAccessors = "0.3.10"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
